Repository JuliaLang/www.julialang.org, pull requests merged in 2020-05, with the labels that each got.

#761 Create help.md
  about/help.md
Labels: enhancement

#803 Use full width for blog posts on mobile
  _layout/head.html
Labels: design, needs feedback

#819 Slightly modified backsplash
  _assets/infra/backsplash-min-0.5.svg
  _css/app.css
Labels: needs feedback
